# Generated by Django 5.0.4 on 2024-04-16 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=100)),
                ('subTitle', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('aboutCourse', models.CharField(max_length=1000)),
                ('duration', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('tech', 'Technology')], max_length=50)),
                ('topics', models.JSONField()),
                ('is_active', models.BooleanField(default=True)),
                ('instructors', models.ManyToManyField(to='edtraaApp.instructor')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('topic', models.CharField(max_length=200)),
                ('timestamp', models.CharField(max_length=10)),
                ('lessonVideoLink', models.URLField(blank=True)),
                ('description', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='edtraaApp.course')),
            ],
        ),
    ]
